name: Test
on:
  push:
    branches: ["test-dev"]
  pull_request: {}
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: Run Test
        run: cd ./src;make ci
